### ISSUE TITLE
when i run build.py , there is a git mistake

### ISSUE THREAD

**Issue by devillove084** [ry/deno#123]
v8/buildtools (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:02] _____ v8/buildtools : Attempting rebase onto f115f4786771afdfacb18a2299541b23e21f4792...
[0:00:02] 
[0:00:02] Rebase produced error output:
Cannot rebase: Your index contains uncommitted changes.
Please commit or stash them.
----------------------------------------
Error: 4> Unrecognized error, please merge or rebase manually.
4> cd ./v8/buildtools && git rebase --onto f115f4786771afdfacb18a2299541b23e21f4792 refs/remotes/origin/master
Traceback (most recent call last):
  File "./build.py", line 149, in <module>
    main()
  File "./build.py", line 85, in main
    lib_fn = Rebuild()
  File "./build.py", line 97, in Rebuild
    EnsureDeps(v8_path)
  File "./build.py", line 146, in EnsureDeps
    env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by JieJiSS** [comment]
@devillove084 I recognized that you have a `Wechat084` repo so I believe that you're in China mainland (me too)

see #126 , holp that can help

**Comment by lvgithub** [comment]
Build Fails,maybe also run

`git submodule update --init` in the v8worker2 dir.
`sudo apt-get install libgtk-3-dev pkg-config ccache` on ubuntu
`sudo yum install libgtk-3-dev pkg-config ccache` on centos
`sudo brew install libgtk-3-dev pkg-config ccache` on macOS

**Comment by devillove084** [comment]
em.........Just build this project in VMs. So i decide to use vpn for the VM.

**Comment by lvgithub** [comment]
https://juejin.im/post/5b15fccbf265da6e1d6ca5b9
