### ISSUE TITLE
Get readFileSync not a function error when tested locally

### ISSUE THREAD

**Issue by kevinkassimo** [ry/deno#150]
The following is the error message when I run `./deno tests.ts`. Seems everything I attempted to import from "deno" is undefined. What could have been the problem? Thanks!

deno_1.readFileSync is not a function TypeError: deno_1.readFileSync is not a function
    at tests_readFileSync (/Users/kevinqian/go/src/github.com/ry/deno/tests.ts:24:29)
    at Object.runTests [as cb] (/Users/kevinqian/go/src/github.com/ry/deno/testing/testing.ts:62:23)

**Comment by kevinkassimo** [comment]
Solved. Should run `make clean` every time before rebuilding
