### ISSUE TITLE
after run ./build.py   get error 

### ISSUE THREAD

**Issue by Ydingguo** [ry/deno#160]
[0:02:16] fatal: index-pack failed
Traceback (most recent call last):
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient_scm.py", line 926, in _Clone
    print_stdout=print_stdout, stdout=stdout)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient_scm.py", line 1230, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient_utils.py", line 314, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient_utils.py", line 576, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/deps/icu.git ./v8/third_party/_gclient_icu_XRvM8e' returned non-zero exit status 128 in .
----------------------------------------
Traceback (most recent call last):
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient.py", line 2947, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient.py", line 2933, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient.py", line 2573, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient.py", line 1559, in RunOnDeps
    patch_refs=patch_refs)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient_utils.py", line 1075, in run
    self.item.run(*self.args, **self.kwargs)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient.py", line 893, in run
    file_list)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient_scm.py", line 130, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient_scm.py", line 445, in update
    self._Clone(revision, url, options)
  File "/root/importgo/src/github.com/ry/v8worker2/depot_tools/gclient_scm.py", line 934, in _Clone
    if os.listdir(tmp_dir):
OSError: [Errno 2] No such file or directory: './v8/third_party/_gclient_icu_XRvM8e'
Traceback (most recent call last):
  File "./build.py", line 149, in <module>
    main()
  File "./build.py", line 85, in main
    lib_fn = Rebuild()
  File "./build.py", line 97, in Rebuild
    EnsureDeps(v8_path)
  File "./build.py", line 146, in EnsureDeps
    env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gclient', 'sync', '--spec', "solutions = [{'managed': False, 'custom_vars': {'build_for_node': True}, 'url': 'https://chromium.googlesource.com/v8/v8.git', 'custom_deps': {'v8/third_party/catapult': None, 'v8/third_party/colorama/src': None, 'v8/testing/gmock': None, 'v8/tools/swarming_client': None, 'v8/third_party/instrumented_libraries': None, 'v8/tools/gyp': None, 'v8/third_party/android_tools': None, 'v8/test/wasm-js': None, 'v8/test/benchmarks/data': None, 'v8/test/mozilla/data': None, 'v8/tools/luci-go': None, 'v8/test/test262/data': None, 'v8/test/test262/harness': None}, 'deps_file': 'DEPS', 'name': 'v8'}]"]' returned non-zero exit status 1

**Comment by terasum** [comment]
@Ydingguo hi, you can try to config the proxy to fetch the v8 source code. something in #145 may help you.

**Comment by FrankFang** [comment]
All you need is a vpn.

**Comment by yaochao** [comment]
I guess you are from China, beacuse me too. Our GCD prevent us from the outside's hurt

**Comment by HongjiangHuang** [comment]
https://github.com/ry/v8worker2/issues/13

**Comment by qti3e** [comment]
we're no longer using V8Worker2
