### ISSUE TITLE
use ./build.py --use_ccache Error

### ISSUE THREAD

**Issue by pandaCure** [ry/deno#230]
I had already set http_proxy and https_proxy in my terminal environment
When i exec this command : python -u ./build.py --use_ccache got such error:

```➜  v8worker2 git:(master) python -u ./build.py --use_ccache
out_path None
Rebuilding V8
Fetching dependencies.
depot_tools update failed. Conflict in /Users/a/go/src/github.com/ry/v8worker2/depot_tools
/Users/a/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:56: trailing whitespace.
   
/Users/a/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:71: trailing whitespace.

/Users/a/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:73: trailing whitespace.
Windows only).
/Users/a/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:77: trailing whitespace.

/Users/a/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:225: trailing whitespace.
 
warning: squelched 596 whitespace errors
warning: 601 lines add whitespace errors.
error: Failed to merge in the changes.
Patch failed at 0001 Create the Next Generation of depot_tools. Eh.
The copy of the patch that failed is found in: /Users/a/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Syncing projects: 100% (24/24), done.                                   

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' in '.'
Failed to fetch file gs://chromium-clang-format/0679b295e2ce2fce7919d1e8d003e497475f24a3 for v8/buildtools/mac/clang-format. [Err: [E2018-06-10T13:24:53.518734+08:00 62191 0 annotate.go:242] original error: request to the backend failed after multiple attempts
[E2018-06-10T13:24:53.519665+08:00 62191 0 annotate.go:242] 
[E2018-06-10T13:24:53.519699+08:00 62191 0 annotate.go:242] goroutine 1:
[E2018-06-10T13:24:53.519716+08:00 62191 0 annotate.go:242] #0 go.chromium.org/luci/cipd/client/cipd/client.go:120 - cipd.init()
[E2018-06-10T13:24:53.519731+08:00 62191 0 annotate.go:242]   tag["this error is temporary"]: true
[E2018-06-10T13:24:53.519747+08:00 62191 0 annotate.go:242] 
[E2018-06-10T13:24:53.519762+08:00 62191 0 annotate.go:242] #1 go.chromium.org/luci/vpython/./<autogenerated>:1 - cipd.init()
[E2018-06-10T13:24:53.519777+08:00 62191 0 annotate.go:242] #2 ./<autogenerated>:1 - main.init()
[E2018-06-10T13:24:53.519791+08:00 62191 0 annotate.go:242] #3 runtime/proc.go:186 - runtime.main()
[E2018-06-10T13:24:53.519803+08:00 62191 0 annotate.go:242]   annotation #0:
[E2018-06-10T13:24:53.519828+08:00 62191 0 annotate.go:242]     reason: failed to resolve packages
[E2018-06-10T13:24:53.519843+08:00 62191 0 annotate.go:242]   annotation #1:
[E2018-06-10T13:24:53.519856+08:00 62191 0 annotate.go:242]     reason: resolving package
[E2018-06-10T13:24:53.519868+08:00 62191 0 annotate.go:242]   annotation #2:
[E2018-06-10T13:24:53.519888+08:00 62191 0 annotate.go:242]     reason: failed to resolve package version (line 0)
[E2018-06-10T13:24:53.519912+08:00 62191 0 annotate.go:242]   annotation #3:
[E2018-06-10T13:24:53.519926+08:00 62191 0 annotate.go:242]     reason: failed to resolve package "infra/python/virtualenv" at version "version:15.1.0"
[E2018-06-10T13:24:53.519952+08:00 62191 0 annotate.go:242] 
[E2018-06-10T13:24:53.519966+08:00 62191 0 annotate.go:242] #4 runtime/asm_amd64.s:2361 - runtime.goexit()
]
0> Failed to fetch file gs://chromium-clang-format/0679b295e2ce2fce7919d1e8d003e497475f24a3 for v8/buildtools/mac/clang-format, skipping. [Err: [E2018-06-10T13:24:53.518734+08:00 62191 0 annotate.go:242] original error: request to the backend failed after multiple attempts
[E2018-06-10T13:24:53.519665+08:00 62191 0 annotate.go:242] 
[E2018-06-10T13:24:53.519699+08:00 62191 0 annotate.go:242] goroutine 1:
[E2018-06-10T13:24:53.519716+08:00 62191 0 annotate.go:242] #0 go.chromium.org/luci/cipd/client/cipd/client.go:120 - cipd.init()
[E2018-06-10T13:24:53.519731+08:00 62191 0 annotate.go:242]   tag["this error is temporary"]: true
[E2018-06-10T13:24:53.519747+08:00 62191 0 annotate.go:242] 
[E2018-06-10T13:24:53.519762+08:00 62191 0 annotate.go:242] #1 go.chromium.org/luci/vpython/./<autogenerated>:1 - cipd.init()
[E2018-06-10T13:24:53.519777+08:00 62191 0 annotate.go:242] #2 ./<autogenerated>:1 - main.init()
[E2018-06-10T13:24:53.519791+08:00 62191 0 annotate.go:242] #3 runtime/proc.go:186 - runtime.main()
[E2018-06-10T13:24:53.519803+08:00 62191 0 annotate.go:242]   annotation #0:
[E2018-06-10T13:24:53.519828+08:00 62191 0 annotate.go:242]     reason: failed to resolve packages
[E2018-06-10T13:24:53.519843+08:00 62191 0 annotate.go:242]   annotation #1:
[E2018-06-10T13:24:53.519856+08:00 62191 0 annotate.go:242]     reason: resolving package
[E2018-06-10T13:24:53.519868+08:00 62191 0 annotate.go:242]   annotation #2:
[E2018-06-10T13:24:53.519888+08:00 62191 0 annotate.go:242]     reason: failed to resolve package version (line 0)
[E2018-06-10T13:24:53.519912+08:00 62191 0 annotate.go:242]   annotation #3:
[E2018-06-10T13:24:53.519926+08:00 62191 0 annotate.go:242]     reason: failed to resolve package "infra/python/virtualenv" at version "version:15.1.0"
[E2018-06-10T13:24:53.519952+08:00 62191 0 annotate.go:242] 
[E2018-06-10T13:24:53.519966+08:00 62191 0 annotate.go:242] #4 runtime/asm_amd64.s:2361 - runtime.goexit()
]
Downloading 1 files took 318.252161 second(s)
Error: Command 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' returned non-zero exit status 1 in .
Hook 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' took 318.34 secs
Traceback (most recent call last):
  File "./build.py", line 152, in <module>
    main()
  File "./build.py", line 88, in main
    lib_fn = Rebuild()
  File "./build.py", line 100, in Rebuild
    EnsureDeps(v8_path)
  File "./build.py", line 149, in EnsureDeps
    env=env)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gclient', 'sync', '--spec', "solutions = [{'managed': False, 'custom_vars': {'build_for_node': True}, 'url': 'https://chromium.googlesource.com/v8/v8.git', 'custom_deps': {'v8/third_party/catapult': None, 'v8/third_party/colorama/src': None, 'v8/testing/gmock': None, 'v8/tools/swarming_client': None, 'v8/third_party/instrumented_libraries': None, 'v8/tools/gyp': None, 'v8/third_party/android_tools': None, 'v8/test/wasm-js': None, 'v8/test/benchmarks/data': None, 'v8/test/mozilla/data': None, 'v8/tools/luci-go': None, 'v8/test/test262/data': None, 'v8/test/test262/harness': None}, 'deps_file': 'DEPS', 'name': 'v8'}]"]' returned non-zero exit status 2```

**Comment by FrankFang** [comment]
download_from_google_storage failed...

If you are in China, please use an oversea vpn. Http/socks proxies doesn't works well for go.
ProtonVPN provides a 7-days free trial plan.

**Comment by pandaCure** [comment]
@FrankFang Thanks  
Solved all my problems
