### ISSUE TITLE
building on mac os fails

### ISSUE THREAD

**Issue by mreinstein** [ry/deno#302]
I'm following the install instructions in the readme. I've got depot tools and yarn installed.

When I run `ninja -C out/Debug/ deno` I get several error referencing `ccache` not found:

```bash
λ ninja -C out/Debug/ deno
ninja: Entering directory `out/Debug/'
[3/792] CXX obj/v8/torque/implementation-visitor.o
FAILED: obj/v8/torque/implementation-visitor.o 
ccache ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/v8/torque/implementation-visitor.o.d -DANTLR4CPP_STATIC -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_LIBCPP_HAS_NO_ALIGNED_ALLOCATION -DCR_XCODE_VERSION=0941 -DCR_CLANG_REVISION=\"332838-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DV8_ENABLE_CHECKS -DV8_EMBEDDER_STRING=\"-deno\" -DENABLE_DISASSEMBLER -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DENABLE_MINOR_MC -DOBJECT_PRINT -DVERIFY_HEAP -DV8_TRACE_MAPS -DV8_ENABLE_ALLOCATION_TIMEOUT -DV8_ENABLE_FORCE_SLOW_PATH -DV8_ENABLE_CHECKS -DENABLE_HANDLE_ZAPPING -DV8_USE_SNAPSHOT -DV8_CONCURRENT_MARKING -DV8_CHECK_MICROTASKS_SCOPES_CONSISTENCY -DV8_TARGET_ARCH_X64 -DDEBUG -DDISABLE_UNTRUSTED_CODE_MITIGATIONS -I../../v8/third_party/antlr4/runtime/Cpp/runtime/src -I../../v8/src/torque -I../.. -Igen -I../../v8/include -Igen/v8/include -I../../v8 -Igen/v8 -fno-strict-aliasing -fstack-protector-strong -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -fmerge-all-constants -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -no-canonical-prefixes -arch x86_64 -Wall -Wextra -Wimplicit-fallthrough -Wthread-safety -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -Wno-enum-compare-switch -Wno-null-pointer-arithmetic -Wno-ignored-pragma-optimize -fno-omit-frame-pointer -g1 -isysroot ../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9.0 -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wmissing-field-initializers -Winconsistent-missing-override -Wunreachable-code -Wshorten-64-to-32 -O3 -fvisibility=default -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14 -stdlib=libc++ -frtti -fexceptions -c ../../v8/src/torque/implementation-visitor.cc -o obj/v8/torque/implementation-visitor.o
/bin/sh: ccache: command not found

(more errors follow ...)
```

Installing ccache via `brew install ccache` and running again produces a new error:

```bash
λ ninja -C out/Debug/ deno
ninja: Entering directory `out/Debug/'
[4/788] ACTION //:deno_stdlib(//build/toolchain/mac:clang_x64)
FAILED: obj/deno_stdlib.a 
python ../../v8/tools/run.py rustc ../../empty.rs --crate-name=deno_stdlib --crate-type=staticlib --emit=dep-info=gen/deno_stdlib.d --emit=link=obj/deno_stdlib.a -g
Traceback (most recent call last):
  File "../../v8/tools/run.py", line 12, in <module>
    sys.exit(subprocess.call(sys.argv[1:]))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[5/788] ACTION //:libc(//build/toolchain/mac:clang_x64)
FAILED: obj/libc.o obj/libc.rlib 
python ../../v8/tools/run.py rustc ../../third_party/rust_crates/libc/src/lib.rs --crate-name=libc --crate-type=rlib --emit=dep-info=gen/libc.d --emit=obj=obj/libc.o --emit=link=obj/libc.rlib -g --cfg feature=\"default\" --cfg feature=\"use_std\"
Traceback (most recent call last):
  File "../../v8/tools/run.py", line 12, in <module>
    sys.exit(subprocess.call(sys.argv[1:]))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[13/788] ACTION //:bundle(//build/toolchain/mac:clang_x64)
⏳  Building...

⏳  Building main.ts...
⏳  Building msg.pb.js...
⏳  Building typescript.js...
⏳  Building minimal.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building _empty.js...
⏳  Building browser.js...
⏳  Building source-map-support.js...
⏳  Building index-minimal.js...
⏳  Building browser.js...
⏳  Building browser.js...
⏳  Building browser.js...
⏳  Building index.js...
⏳  Building browser.js...
⏳  Building browser.js...
⏳  Building browser.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building browser.js...
⏳  Building index.js...
⏳  Building browser.js...
⏳  Building algos.js...
⚠️  /Users/michaelreinstein/wwwroot/deno/src/js/node_modules/source-map-support/source-map-support.js:84:33: Cannot statically evaluate fs argument
  82 |     // Otherwise, use the filesystem
  83 |     try {
> 84 |       contents = fs.readFileSync(path, 'utf8');
     |                                  ^
  85 |     } catch (er) {
  86 |       contents = '';
  87 |     }
⚠️  /Users/michaelreinstein/wwwroot/deno/src/js/node_modules/source-map-support/source-map-support.js:396:35: Cannot statically evaluate fs argument
  394 |     if (!contents && fs && fs.existsSync(source)) {
  395 |       try {
> 396 |         contents = fs.readFileSync(source, 'utf8');
      |                                    ^
  397 |       } catch (er) {
  398 |         contents = '';
  399 |       }
⏳  Building browser.js...
⏳  Building index.js...
⏳  Building source-map.js...
⏳  Building writer.js...
⏳  Building writer_buffer.js...
⏳  Building reader.js...
⏳  Building reader_buffer.js...
⏳  Building rpc.js...
⏳  Building roots.js...
⏳  Building minimal.js...
⏳  Building legacy.js...
⏳  Building primes.json...
⏳  Building algorithms.json...
⏳  Building generatePrime.js...
⏳  Building dh.js...
⏳  Building publicEncrypt.js...
⏳  Building privateDecrypt.js...
⏳  Building async.js...
⏳  Building sync-browser.js...
⏳  Building md5.js...
⏳  Building inherits_browser.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building elliptic.js...
⏳  Building bn.js...
⏳  Building index.js...
⏳  Building browser.js...
⏳  Building modes.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building source-map-generator.js...
⏳  Building source-map-consumer.js...
⏳  Building source-node.js...
⏳  Building sign.js...
⏳  Building verify.js...
⏳  Building index.js...
⏳  Building mgf.js...
⏳  Building xor.js...
⏳  Building withPublic.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building list.json...
⏳  Building encrypter.js...
⏳  Building decrypter.js...
⏳  Building sha.js...
⏳  Building sha1.js...
⏳  Building sha224.js...
⏳  Building sha256.js...
⏳  Building sha384.js...
⏳  Building sha512.js...
⏳  Building service.js...
⏳  Building string_decoder.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building des.js...
⏳  Building precondition.js...
⏳  Building default-encoding.js...
⏳  Building package.json...
⏳  Building mr.js...
⏳  Building utils.js...
⏳  Building curves.js...
⏳  Building events.js...
⏳  Building longbits.js...
⏳  Building base64-vlq.js...
⏳  Building util.js...
⏳  Building array-set.js...
⏳  Building mapping-list.js...
⏳  Building readable-browser.js...
⏳  Building writable-browser.js...
⏳  Building duplex-browser.js...
⏳  Building binary-search.js...
⏳  Building quick-sort.js...
⏳  Building passthrough.js...
⏳  Building transform.js...
⏳  Building index.js...
⏳  Building curves.json...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building authCipher.js...
⏳  Building streamCipher.js...
⏳  Building aes.js...
⏳  Building aesid.json...
⏳  Building hash.js...
⏳  Building asn1.js...
⏳  Building fixProc.js...
⏳  Building ecb.js...
⏳  Building cbc.js...
⏳  Building cfb.js...
⏳  Building cfb8.js...
⏳  Building cfb1.js...
⏳  Building ofb.js...
⏳  Building ctr.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building utils.js...
⏳  Building cipher.js...
⏳  Building des.js...
⏳  Building cbc.js...
⏳  Building ede.js...
⏳  Building index.js...
⏳  Building utils.js...
⏳  Building base64.js...
⏳  Building secp256k1.js...
⏳  Building _stream_readable.js...
⏳  Building _stream_writable.js...
⏳  Building _stream_duplex.js...
⏳  Building _stream_transform.js...
⏳  Building _stream_passthrough.js...
⏳  Building hash.js...
⏳  Building ghash.js...
⏳  Building incr32.js...
⏳  Building index.js...
⏳  Building certificate.js...
⏳  Building asn1.js...
⏳  Building base.js...
⏳  Building short.js...
⏳  Building mont.js...
⏳  Building edwards.js...
⏳  Building stream-browser.js...
⏳  Building BufferList.js...
⏳  Building destroy.js...
⏳  Building signature.js...
⏳  Building key.js...
⏳  Building index.js...
⏳  Building util.js...
⏳  Building utils.js...
⏳  Building common.js...
⏳  Building sha.js...
⏳  Building ripemd.js...
⏳  Building hmac.js...
⏳  Building hmac-drbg.js...
⏳  Building key.js...
⏳  Building signature.js...
⏳  Building browser.js...
⏳  Building api.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building reporter.js...
⏳  Building buffer.js...
⏳  Building node.js...
⏳  Building der.js...
⏳  Building der.js...
⏳  Building pem.js...
⏳  Building der.js...
⏳  Building pem.js...
⏳  Building 1.js...
⏳  Building 224.js...
⏳  Building 256.js...
⏳  Building 384.js...
⏳  Building 512.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building common.js...
✨  Built in 22.63s.

gen/bundle/main.js     ⚠️  6.77 MB    120.93s
gen/bundle/main.map           0 B    120.03s
ninja: build stopped: subcommand failed.
```

Any ideas?

**Comment by kevinkassimo** [comment]
Seems to be complaining missing `src/v8/tools/run.py`. Have you run `gclient sync --no-history`?

**Comment by mreinstein** [comment]
yes

**Comment by mreinstein** [comment]
relevant contents of my `~/.bashrc`:

```bash
export PATH=$PATH:/Users/michaelreinstein/wwwroot/depot_tools

export PATH=/usr/local/bin:$PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export PATH="/usr/local/sbin:$PATH"
```
Am I missing something here maybe?

**Comment by kevinkassimo** [comment]
@mreinstein can you check if `v8/tools/run.py` actually exists? And which directory are you in when you run `ninja`?

**Comment by mreinstein** [comment]
> can you check if v8/tools/run.py actually exists?

yep, seems to:

```bash
λ ls v8/tools/run.py 
v8/tools/run.py
```


>  which directory are you in when you run ninja?

I'm following the build instructions as carefully as possible; I'm in`deno/src/` when running these commands.

**Comment by kevinkassimo** [comment]
> I'm following the build instructions as carefully as possible; I'm indeno/src/ when running these commands.

Interesting. I just made a fresh clone of the repo and run the build steps myself, but cannot reproduce the issue. Probably pull latest commits from master?

**Comment by mreinstein** [comment]
> Probably pull latest commits from master?

from the deno repo? I've got latest.

I suspect this must have something to do with my build tools not being set up correctly.

**Comment by mreinstein** [comment]
One thing I noticed is that ccache need to be installed from git head. so I've done that, replacing `brew install ccache` with `brew install --HEAD ccache`. Now I get a different error:

```bash
λ ninja -C out/Debug/ deno
ninja: Entering directory `out/Debug/'
[1/715] ACTION //:deno_stdlib(//build/toolchain/mac:clang_x64)
FAILED: obj/deno_stdlib.a 
python ../../v8/tools/run.py rustc ../../empty.rs --crate-name=deno_stdlib --crate-type=staticlib --emit=dep-info=gen/deno_stdlib.d --emit=link=obj/deno_stdlib.a -g
Traceback (most recent call last):
  File "../../v8/tools/run.py", line 12, in <module>
    sys.exit(subprocess.call(sys.argv[1:]))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2/715] ACTION //:libc(//build/toolchain/mac:clang_x64)
FAILED: obj/libc.o obj/libc.rlib 
python ../../v8/tools/run.py rustc ../../third_party/rust_crates/libc/src/lib.rs --crate-name=libc --crate-type=rlib --emit=dep-info=gen/libc.d --emit=obj=obj/libc.o --emit=link=obj/libc.rlib -g --cfg feature=\"default\" --cfg feature=\"use_std\"
Traceback (most recent call last):
  File "../../v8/tools/run.py", line 12, in <module>
    sys.exit(subprocess.call(sys.argv[1:]))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[10/715] CXX obj/v8/src/inspector/inspector/Profiler.o
ninja: build stopped: subcommand failed.
```

**Comment by ry** [comment]
Your missing rustc

The Travis file will have hints for installing deps and such
