### ISSUE TITLE
Run `gn gen out/Default` and get error : `... AttributeError: 'NoneType' object has no attribute 'endswith'`

### ISSUE THREAD

**Issue by guitong** [ry/deno#358]
I cloned the depot_tools repository, and put this in my `.zshrc` file:

`export PATH=$PATH:/mypath/depot_tools`

when i run `gn gen out/Default`,  got this error: 

```
Traceback (most recent call last):
  File "/Users/gui/workSpace/libs/depot_tools/gn.py", line 71, in <module>
    sys.exit(main(sys.argv))
  File "/Users/gui/workSpace/libs/depot_tools/gn.py", line 49, in main
    'gn', 'gn' + gclient_utils.GetExeSuffix())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by ry** [comment]
Run `./tools/build_third_party.py` sorry for the weird error message.
