### ISSUE TITLE
run_hooks.py fails

### ISSUE THREAD

**Issue by est31** [ry/deno#407]
I've tried building deno as described in the README. Running `run_hooks.py` gives me the following error:

```
python ~/src/deno/third_party/depot_tools/download_from_google_storage.py --platform=linux2 --no_auth --bucket=chromium-gn --sha1_file ~/src/deno/third_party/v8/buildtools/linux64/gn.sha1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "~/src/deno/third_party/depot_tools/download_from_google_storage.py", line 250, in _downloader_worker_thread
    (code, _, err) = gsutil.check_call('ls', file_url)
  File "~/src/deno/third_party/depot_tools/download_from_google_storage.py", line 110, in check_call
    timeout=self.timeout)
  File "~/src/deno/third_party/depot_tools/subprocess2.py", line 458, in communicate
    proc = Popen(args, **kwargs)
  File "~/src/deno/third_party/depot_tools/subprocess2.py", line 262, in __init__
    % (str(e), kwargs.get('cwd'), args[0]))
OSError: Execution failed with error: [Errno 2] No such file or directory.
Check that None or vpython exist and have execution permission.

python third_party/v8/tools/clang/scripts/update.py --if-needed
```

**Comment by ry** [comment]
I believe this will be fixed when #406 lands. Sorry about that.

**Comment by ry** [comment]
#406 has landed. reopen if this is still a problem.

**Comment by est31** [comment]
This is fixed now, thanks! Running into other problems now, though.
