### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by aledbf** [ry/deno#59]
Hi, I am trying to build locally but I get the next error and I am not sure if this is my fault or not :)

```
$ go get -d github.com/ry/v8worker2 || true
# cd /go/src/github.com/ry/v8worker2; git submodule update --init --recursive
Submodule 'depot_tools' (https://chromium.googlesource.com/chromium/tools/depot_tools.git) registered for path 'depot_tools'
Submodule 'v8' (https://github.com/v8/v8.git) registered for path 'v8'
Cloning into '/go/src/github.com/ry/v8worker2/depot_tools'...
Cloning into '/go/src/github.com/ry/v8worker2/v8'...
From https://chromium.googlesource.com/chromium/tools/depot_tools
 * branch              f16fdf3165b8b86d10386d18a6b6075169c10e15 -> FETCH_HEAD
Submodule path 'depot_tools': checked out 'f16fdf3165b8b86d10386d18a6b6075169c10e15'
error: no such remote ref fe12316ec4b4a101923e395791ca55442e62f4cc
Fetched in submodule path 'v8', but it did not contain fe12316ec4b4a101923e395791ca55442e62f4cc. Direct fetching of that commit failed.
package github.com/ry/v8worker2: exit status 1

cd $GOPATH/src/github.com/ry/v8worker2    && ./build.py --use_ccache --out_path $V8WORKER2_OUT_PATH
depot_tools update failed. Conflict in /go/src/github.com/ry/v8worker2/depot_tools
/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:56: trailing whitespace.
   
/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:71: trailing whitespace.

/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:73: trailing whitespace.
Windows only).
/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:77: trailing whitespace.

/go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch:225: trailing whitespace.
 
warning: squelched 596 whitespace errors
warning: 601 lines add whitespace errors.
error: Failed to merge in the changes.
Patch failed at 0001 Create the Next Generation of depot_tools. Eh.
The copy of the patch that failed is found in: /go/src/github.com/ry/v8worker2/.git/modules/depot_tools/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Bootstrapping cipd client for linux-amd64 from https://chrome-infra-packages.appspot.com/client?platform=linux-amd64&version=git_revision:4d19637ec2c3d1efd8c6a1b05285118b786919e2...
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.
out_path ['/v8worker2_out']
Rebuilding V8
Fetching dependencies.
Running gn
Traceback (most recent call last):
  File "./build.py", line 149, in <module>
    main()
  File "./build.py", line 85, in main
    lib_fn = Rebuild()
  File "./build.py", line 114, in Rebuild
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/go/src/github.com/ry/v8worker2/depot_tools/gn', 'gen', '/v8worker2_out/v8build', '--args=   is_component_build=false   is_debug=false   libcpp_is_static=false   symbol_level=1   treat_warnings_as_errors=false   use_custom_libcxx=false   use_sysroot=false   v8_deprecation_warnings=false   v8_embedder_string="-v8worker2"   v8_enable_gdbjit=false   v8_enable_i18n_support=false   v8_enable_test_features=false   v8_experimental_extra_library_files=[]   v8_extra_library_files=[]   v8_imminent_deprecation_warnings=false   v8_monolithic=true   v8_static_library=false   v8_target_cpu="x64"   v8_untrusted_code_mitigations=false   v8_use_external_startup_data=false   v8_use_snapshot=true  cc_wrapper="/usr/bin/ccache"']' returned non-zero exit status 1
```

What I should check?
Thans in advance

**Comment by aledbf** [comment]
Closing. This was an issue with debian strech. Using ubuntu 18.04 works just fine.
